name: alfaisal_for_advertising
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0' 

dependencies:
  flutter:
    sdk: flutter 
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.0 
  riverpod_annotation: ^2.0.0
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  wechat_assets_picker : ^8.4.0  
  logger: ^1.1.0 
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  sentry_flutter: ^6.20.1  
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  internet_connection_checker_plus: ^1.0.1
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^7.0.1
  intl: ^0.17.0
  dartz: ^0.10.1
  go_router: ^6.2.0
  lottie: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0 
  custom_lint: ^0.2.12
  freezed: ^2.3.2 
  riverpod_generator: ^2.0.0
  riverpod_lint: ^1.1.2
  flutter_native_splash: ^2.2.16
  build_runner: ^2.3.3
  requests_inspector: ^2.3.5 
  json_serializable: ^6.6.1

flutter: 
  uses-material-design: true
  generate: true # generates flutter localizations 

flutter_native_splash:
  color: "#FFFFFF"
  web: false
  android_disable_fullscreen: false
  image: assets/icons/logo.png
  android_12:
    image: assets/icons/logo1.png
    color: "#FFFFFF"

  assets:
    - assets/icons/  
    - assets/images/
    - assets/animations/   
  